# Generated by Django 5.2.3 on 2025-06-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refshop',
            name='name',
        ),
    ]
